import Foundation

enum SeedPlaces {
    static let all: [Place] = [
        Place(
            id: "paris_louvre",
            source: .localSeed,
            sourcePlaceID: "paris_louvre",
            name: "Louvre Museum",
            category: .museum,
            latitude: 48.8606,
            longitude: 2.3376,
            address: "Rue de Rivoli, Paris",
            rating: 4.8,
            priceLevel: 3,
            isOpenNow: true,
            tags: ["classic", "art", "museum", "must-see", "photo"],
            summary: "Major art museum and one of the strongest classic stops in central Paris."
        ),
        Place(
            id: "paris_tuileries",
            source: .localSeed,
            sourcePlaceID: "paris_tuileries",
            name: "Tuileries Garden",
            category: .park,
            latitude: 48.8635,
            longitude: 2.3270,
            address: "Place de la Concorde, Paris",
            rating: 4.6,
            priceLevel: 0,
            isOpenNow: true,
            tags: ["relaxed", "walk", "garden", "photo"],
            summary: "A relaxed garden walk that pairs well with the Louvre and central landmarks."
        ),
        Place(
            id: "paris_orsay",
            source: .localSeed,
            sourcePlaceID: "paris_orsay",
            name: "Musee d'Orsay",
            category: .museum,
            latitude: 48.8600,
            longitude: 2.3266,
            address: "1 Rue de la Legion d'Honneur, Paris",
            rating: 4.8,
            priceLevel: 3,
            isOpenNow: true,
            tags: ["art", "classic", "museum", "impressionist"],
            summary: "A classic art museum in a former railway station, close to the Seine."
        ),
        Place(
            id: "paris_seine_view",
            source: .localSeed,
            sourcePlaceID: "paris_seine_view",
            name: "Pont des Arts View",
            category: .viewpoint,
            latitude: 48.8584,
            longitude: 2.3375,
            address: "Pont des Arts, Paris",
            rating: 4.5,
            priceLevel: 0,
            isOpenNow: true,
            tags: ["photo", "romantic", "seine", "view"],
            summary: "A compact photo-friendly Seine viewpoint near the Louvre."
        ),
        Place(
            id: "paris_cafe_marly",
            source: .localSeed,
            sourcePlaceID: "paris_cafe_marly",
            name: "Cafe Marly",
            category: .restaurant,
            latitude: 48.8617,
            longitude: 2.3358,
            address: "93 Rue de Rivoli, Paris",
            rating: 4.1,
            priceLevel: 4,
            isOpenNow: true,
            tags: ["meal", "view", "classic", "photo"],
            summary: "A scenic meal stop beside the Louvre courtyard."
        ),
        Place(
            id: "paris_telescope_cafe",
            source: .localSeed,
            sourcePlaceID: "paris_telescope_cafe",
            name: "Telescope Cafe",
            category: .cafe,
            latitude: 48.8654,
            longitude: 2.3358,
            address: "5 Rue Villedo, Paris",
            rating: 4.5,
            priceLevel: 2,
            isOpenNow: true,
            tags: ["coffee", "local", "relaxed", "mid-budget"],
            summary: "A compact coffee stop for a lighter route between landmarks."
        ),
        Place(
            id: "shanghai_bund",
            source: .localSeed,
            sourcePlaceID: "shanghai_bund",
            name: "The Bund",
            category: .viewpoint,
            latitude: 31.2401,
            longitude: 121.4908,
            address: "Zhongshan East 1st Road, Shanghai",
            rating: 4.7,
            priceLevel: 0,
            isOpenNow: true,
            tags: ["skyline", "photo", "classic", "walk"],
            summary: "Shanghai skyline viewpoint and a strong first stop for city walks."
        ),
        Place(
            id: "shanghai_yuyuan",
            source: .localSeed,
            sourcePlaceID: "shanghai_yuyuan",
            name: "Yu Garden",
            category: .attraction,
            latitude: 31.2272,
            longitude: 121.4921,
            address: "279 Yuyuan Old Street, Shanghai",
            rating: 4.5,
            priceLevel: 2,
            isOpenNow: true,
            tags: ["classic", "garden", "history", "photo"],
            summary: "Historic garden and old-city area with dense sightseeing value."
        ),
        Place(
            id: "shanghai_m_pop",
            source: .localSeed,
            sourcePlaceID: "shanghai_m_pop",
            name: "M on the Bund",
            category: .restaurant,
            latitude: 31.2344,
            longitude: 121.4900,
            address: "Guangdong Road, Shanghai",
            rating: 4.4,
            priceLevel: 4,
            isOpenNow: true,
            tags: ["view", "meal", "romantic", "photo"],
            summary: "A restaurant option with strong Bund views for a scenic route."
        ),
        Place(
            id: "tokyo_sensoji",
            source: .localSeed,
            sourcePlaceID: "tokyo_sensoji",
            name: "Senso-ji",
            category: .attraction,
            latitude: 35.7148,
            longitude: 139.7967,
            address: "Asakusa, Tokyo",
            rating: 4.6,
            priceLevel: 0,
            isOpenNow: true,
            tags: ["classic", "temple", "photo", "culture"],
            summary: "A classic Tokyo temple stop with strong street-level exploration nearby."
        ),
        Place(
            id: "tokyo_kappabashi",
            source: .localSeed,
            sourcePlaceID: "tokyo_kappabashi",
            name: "Kappabashi Kitchen Street",
            category: .shopping,
            latitude: 35.7134,
            longitude: 139.7899,
            address: "Taito City, Tokyo",
            rating: 4.3,
            priceLevel: 2,
            isOpenNow: true,
            tags: ["local", "shopping", "walk", "hidden-gem"],
            summary: "A local-feeling shopping street that works well after Asakusa."
        ),
        Place(
            id: "nyc_met",
            source: .localSeed,
            sourcePlaceID: "nyc_met",
            name: "The Metropolitan Museum of Art",
            category: .museum,
            latitude: 40.7794,
            longitude: -73.9632,
            address: "1000 5th Ave, New York",
            rating: 4.8,
            priceLevel: 3,
            isOpenNow: true,
            tags: ["classic", "art", "museum", "rainy-day"],
            summary: "A high-value museum anchor for an Upper East Side route."
        ),
        Place(
            id: "nyc_central_park",
            source: .localSeed,
            sourcePlaceID: "nyc_central_park",
            name: "Central Park",
            category: .park,
            latitude: 40.7829,
            longitude: -73.9654,
            address: "Central Park, New York",
            rating: 4.8,
            priceLevel: 0,
            isOpenNow: true,
            tags: ["relaxed", "walk", "park", "photo"],
            summary: "A flexible park segment that keeps the route from feeling too dense."
        )
    ]
}
